load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "practice_examples",
    srcs = ["practice_examples.cc"],
    hdrs = ["practice_examples.h"],
    visibility = ["//visibility:public"],
)
